Repository cloudify-cosmo/cloudify-ansible-plugin, pull requests merged in 2022-06, with the labels that each got.

#128 RD-4902-provide-parameters-for-ansible-reload-workflow
  .gitignore
  CHANGELOG.txt
  cloudify_ansible/__init__.py
  cloudify_ansible/tests/test_decorators.py
  cloudify_ansible/tests/test_tasks.py
  cloudify_ansible/utils.py
  cloudify_ansible/workflows.py
  plugin.yaml
Labels: bug

#127 add v2_plugin.yaml and new types
  .circleci/config.yml
  CHANGELOG.txt
  ignore_plugin_yaml_differences
  v2_plugin.yaml
Labels: experimental

#129 RD-5076-ansible-plugin-should-combine-previous-parameters-with-new-parameters
  CHANGELOG.txt
  cloudify_ansible/workflows.py
Labels: bug

#130 update circleci
  .circleci/config.yml
Labels: core
